### ISSUE TITLE
npm install compile error

### ISSUE THREAD

**Issue by rpelissi** [rancher/longhorn-ui#13]
Hi,
running on debian stretch/sid

When trying to use 
`npm install`
 I got this:

```
root@pdrrancher001:~/longhorn-ui# npm install

> husky@0.12.0 install /root/longhorn-ui/node_modules/husky
> node ./bin/install.js

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.3
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was installed.
npm ERR! Linux 4.4.0-119-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.12.0 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the husky@0.12.0 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs husky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/longhorn-ui/npm-debug.log
```

The log show this:

```
448 verbose stack Error: husky@0.12.0 install: `node ./bin/install.js`
448 verbose stack spawn ENOENT
448 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
448 verbose stack     at emitTwo (events.js:87:13)
448 verbose stack     at ChildProcess.emit (events.js:172:7)
448 verbose stack     at maybeClose (internal/child_process.js:821:16)
448 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
449 verbose pkgid husky@0.12.0
450 verbose cwd /root/longhorn-ui
451 error Linux 4.4.0-119-generic
452 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
453 error node v4.2.6
454 error npm  v3.5.2
455 error file sh
456 error code ELIFECYCLE
457 error errno ENOENT
458 error syscall spawn
459 error husky@0.12.0 install: `node ./bin/install.js`
459 error spawn ENOENT
460 error Failed at the husky@0.12.0 install script 'node ./bin/install.js'.
460 error Make sure you have the latest version of node.js and npm installed.
460 error If you do, this is most likely a problem with the husky package,
460 error not with npm itself.
460 error Tell the author that this fails on your system:
460 error     node ./bin/install.js
460 error You can get information on how to open an issue for this project with:
460 error     npm bugs husky
460 error Or if that isn't available, you can get their info via:
460 error     npm owner ls husky
460 error There is likely additional logging output above.
461 verbose exit [ 1, true ]
```

**Comment by yasker** [comment]
Please try `make`.
